### ISSUE TITLE
关于数字图像处理考试

### ISSUE THREAD

**Issue by Arrosw** [jyfzh/nvim#1]
Hi学长，想问一下数字图像处理考试计算题多吗？考试难不难？感谢！

**Comment by jyfzh** [comment]
我那年基本全都是主观题，计算题不多。不是很难的考试，好好复习就行。😊

________________________________
发件人: Arrosw ***@***.***>
发送时间: 2024年12月5日 14:21
收件人: jyfzh/nvim ***@***.***>
抄送: Subscribed ***@***.***>
主题: [jyfzh/nvim] 关于数字图像处理考试 (Issue #1)


Hi学长，想问一下数字图像处理考试计算题多吗？考试难不难？感谢！
